name: Continuous tests
on:
  - push
  - pull_request
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and test
    steps:
      - uses: actions/checkout@v2
      - name: Set yarn cache directory
        run: echo "::set-env name=YARN_CACHE::$(yarn cache dir)"
      - name: Cache node modules
        id: lerna-yarn-cache
        uses: actions/cache@v2
        env:
            cache-name: cache-node-modules
        with:
            path: |
                ${{ env.YARN_CACHE }}
                node_modules
                */*/node_modules
            key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
            restore-keys: |
                ${{ runner.os }}-build-${{ env.cache-name }}-
                ${{ runner.os }}-build-
                ${{ runner.os }}-
      - name: Install dependencies if needed.
        if: steps.lerna-yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --ignore-platform --frozen-lockfile
      - run: yarn build
      - run: yarn --force
      - run: yarn run test