name: Continuous tests
on:
  - push
  - pull_request
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and test
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      
      - name: Yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}-v3
          restore-keys: |
            ${{ runner.os }}-yarn-
      
      - name: Dependencies cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-deps-${{ hashFiles('**/yarn.lock') }}-v3
      
      - name: Install
        run: yarn --frozen-lockfile --prefer-offline 

      - name: Lint
        run: yarn run lint

      - name: Build
        run: |
          yarn build
          yarn run link

      - name: Run tests
        run: yarn run test
